name: CI

on:
  push:
    paths:
      - '*.txt'
      - '*.xml'
  pull_request:
    paths:
      - '*.txt'
      - '*.xml'

jobs:
  make_xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}
    - name: create xml files and push
      run: | 
        scripts/makeLegacyFormats.sh
        git config user.email "efucile@wmo.int"
        git config user.name "Enrico Fucile"
        git add .
        git commit -m "xml,txt files" -a
        git push
